DROP TABLE IF EXISTS contact; 
DROP TABLE IF EXISTS user; 

CREATE TABLE user (
    user_no BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,

    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE contact (
    contact_no BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    img VARCHAR(255) NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    company VARCHAR(255) NULL,
    position VARCHAR(255) NULL,
    memo VARCHAR(255) NULL,
    address VARCHAR(255) NULL,
    DOB VARCHAR(255) NULL,
    website VARCHAR(255) NULL,
    label JSON NULL DEFAULT (JSON_ARRAY('default')), 

    user_no BIGINT NOT NULL,
    INDEX (user_no),
    CONSTRAINT `contanct_ibfk_1` FOREIGN KEY (`user_no`)
    REFERENCES `user` (`user_no`) ON DELETE CASCADE,

    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

